### ISSUE TITLE
No Web page for only Networking

### ISSUE THREAD

**Issue by Avinash4c9** [dbretty/EUCMonitoring#24]
Code is not letting me generate html page for Networking components only , and even the final page should show only networking workloads on final web html page..

**Comment by littletoyrobots** [comment]
Can you confirm that in your euc-monitoring.json that citrix.global.workloads is empty?

`            "workloads": [],`

**Comment by Avinash4c9** [comment]
Yes..it is empty..please find the below
"Global": {
            "xdbrokerprimary": "10.XXX.XXX.XXX",
            "xdbrokerfailover": "xdsecondary.domain.com",
            "workloads": ["server"],
            "controlup": "no"

**Comment by littletoyrobots** [comment]
Will you try removing the workload "server" so that the value is the empty set, and retry? I hope I understand what you're trying to do, in trying to only monitor the netscalers and not see any other Citrix resource type information.

**Comment by wilkyit** [comment]
i am getting the below trying to connect , even if i have not selected any Citrix tests to be performed.
"xdbrokerprimary": "10.XXX.XXX.XXX",
"xdbrokerfailover": "xdsecondary.domain.com".

I think Line 238-468 just needs to be wrapped in check to if global citrix test is yes then run it otherwise end and check microsoft
